name: Docker Build

on:
    push:
        branches: [dev, main]

concurrency:
    group: docker-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get Version
              id: version
              run: bash scripts/docker/get-version.sh

            - name: Check Latest
              id: skip_main
              if: github.ref == 'refs/heads/main'
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                  VERSION: ${{ steps.version.outputs.version }}
              run: bash scripts/docker/check-skip-build.sh

            - name: Set Release Tags
              id: tags
              if: github.ref != 'refs/heads/main' || steps.skip_main.outputs.skip_build != 'true'
              env:
                  VERSION: ${{ steps.version.outputs.version }}
              run: bash scripts/docker/set-tags.sh

            - name: Set up Docker Build
              if: github.ref != 'refs/heads/main' || steps.skip_main.outputs.skip_build != 'true'
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              if: github.ref != 'refs/heads/main' || steps.skip_main.outputs.skip_build != 'true'
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              if: github.ref != 'refs/heads/main' || steps.skip_main.outputs.skip_build != 'true'
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: docker/Dockerfile
                  platforms: linux/amd64
                  build-args: |
                      APP_URL=http://localhost
                      API_PORT=3210
                      VERSION=${{ steps.version.outputs.version }}
                  tags: ${{ steps.tags.outputs.tag_list }}
                  push: true
